# ============================================
# StockPredictionPro - environment.yml
# Conda environment specification
# Alternative to pip requirements.txt
# ============================================

name: stockpredictionpro
channels:
  - conda-forge
  - defaults
  - plotly
  - pyviz

dependencies:
  # -------------------------------
  # Python version
  # -------------------------------
  - python=3.11

  # -------------------------------
  # Core scientific stack
  # -------------------------------
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - scikit-learn=1.5.1
  - joblib=1.4.2
  - tqdm=4.66.4

  # -------------------------------
  # Web UI and visualization
  # -------------------------------
  - streamlit=1.37.1
  - plotly=5.23.0

  # -------------------------------
  # HTTP clients and API
  # -------------------------------
  - requests=2.32.3
  - httpx=0.27.0
  - fastapi=0.112.2
  - uvicorn=0.30.6
  - pydantic=2.8.2

  # -------------------------------
  # Configuration and environment
  # -------------------------------
  - python-dotenv=1.0.1
  - pyyaml=6.0.2

  # -------------------------------
  # Machine learning optimization
  # -------------------------------
  - optuna=3.6.1

  # -------------------------------
  # Logging and observability
  # -------------------------------
  - loguru=0.7.2
  - structlog=24.4.0

  # -------------------------------
  # Development tools
  # -------------------------------
  - black=24.8.0
  - isort=5.13.2
  - flake8=7.1.1
  - mypy=1.11.2
  - pre-commit=3.8.0
  - yamllint=1.35.1

  # -------------------------------
  # Testing framework
  # -------------------------------
  - pytest=8.3.2
  - pytest-cov=5.0.0
  - pytest-mock=3.14.0
  - pytest-asyncio=0.24.0

  # -------------------------------
  # Packaging and deployment
  # -------------------------------
  - pyinstaller=6.10.0

  # -------------------------------
  # Optional: Database and caching (commented out by default)
  # -------------------------------
  # - redis-py=5.0.8
  # - sqlalchemy=2.0.32
  # - psycopg2=2.9.9

  # -------------------------------
  # Optional: Advanced ML (uncomment if using)
  # -------------------------------
  # - xgboost=2.1.1
  # - lightgbm=4.5.0

  # -------------------------------
  # Pip-only packages (not available in conda)
  # -------------------------------
  - pip
  - pip:
    # Financial data sources
    - yfinance==0.2.43
    
    # Technical analysis indicators
    - ta==0.11.0
    - pandas-ta==0.3.14b0
    
    # Model interpretability
    - shap==0.46.0
    
    # Monitoring and error tracking
    - sentry-sdk==2.13.0
    - prometheus-client==0.20.0
    
    # Docker integration
    - docker==7.1.0
    
    # Optional: TA-Lib (requires system libraries)
    # - TA-Lib==0.4.32

# -------------------------------
# Environment variables (optional)
# -------------------------------
variables:
  PYTHONPATH: $CONDA_PREFIX/src
  STREAMLIT_SERVER_HEADLESS: true
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
