app:
  name: StockPredictionPro
  version: 1.0.0
  environment: ${ENVIRONMENT:development}
  debug: true
  timezone: ${APP_TIMEZONE:Asia/Kolkata}
data_sources:
  yahoo_finance:
    enabled: true
    timeout: 30
    retries: 3
    cache_ttl: 3600
  alpha_vantage:
    enabled: true
    api_key: ${ALPHA_VANTAGE_KEY:}
    rate_limit: 5
markets:
  default_market: ${DEFAULT_MARKET:NSE}
  default_symbols: ${DEFAULT_TICKERS:AAPL,MSFT,INFY.NS,TCS.NS}
caching:
  enabled: true
  backend:
    type: memory
  ttl:
    stock_data: 3600
