# ============================================
# StockPredictionPro - app_config.yaml
# Main application configuration
# ============================================

# -------------------------------
# Application Metadata
# -------------------------------
app:
  name: "StockPredictionPro"
  version: "1.0.0"
  description: "Advanced Stock Market Prediction with ML Models"
  author: "Mohd Faraz"
  license: "MIT"
  repository: "https://github.com/Faraazz05/StockPredictionPro"
  
  # Environment configuration
  environment: "${ENVIRONMENT:development}"  # development, production, testing
  debug: true
  log_level: "${LOG_LEVEL:INFO}"  # DEBUG, INFO, WARNING, ERROR
  
  # Timezone and locale
  timezone: "${APP_TIMEZONE:Asia/Kolkata}"
  locale: "${APP_LOCALE:en_IN}"

# -------------------------------
# Data Sources Configuration
# -------------------------------
data_sources:
  # Primary data source (free, no API key required)
  yahoo_finance:
    enabled: true
    timeout: 30
    retries: 3
    cache_ttl: 3600  # 1 hour
    base_url: "https://query1.finance.yahoo.com"
    
  # Secondary/fallback data source
  alpha_vantage:
    enabled: true
    api_key: "${ALPHA_VANTAGE_KEY:}"  # Optional from .env
    timeout: 30
    retries: 2
    rate_limit: 5  # calls per minute (free tier)
    base_url: "https://www.alphavantage.co/query"
    
  # Future data sources (disabled by default)
  polygon:
    enabled: false
    api_key: "${POLYGON_API_KEY:}"
    
  quandl:
    enabled: false
    api_key: "${QUANDL_API_KEY:}"
    
  fred:
    enabled: false
    api_key: "${FRED_API_KEY:}"

# -------------------------------
# Default Market & Symbols
# -------------------------------
markets:
  default_market: "${DEFAULT_MARKET:NSE}"  # NSE (India), US (United States)
  
  # Predefined symbol lists for quick selection
  symbol_lists:
    us_popular:
      - "AAPL"   # Apple Inc.
      - "MSFT"   # Microsoft Corporation
      - "GOOGL"  # Alphabet Inc.
      - "AMZN"   # Amazon.com Inc.
      - "TSLA"   # Tesla Inc.
      - "META"   # Meta Platforms Inc.
      - "NVDA"   # NVIDIA Corporation
      - "NFLX"   # Netflix Inc.
      
    india_nse:
      - "INFY.NS"      # Infosys Limited
      - "TCS.NS"       # Tata Consultancy Services
      - "RELIANCE.NS"  # Reliance Industries
      - "HDFCBANK.NS"  # HDFC Bank Limited
      - "WIPRO.NS"     # Wipro Limited
      - "ITC.NS"       # ITC Limited
      - "SBIN.NS"      # State Bank of India
      - "BHARTIARTL.NS" # Bharti Airtel
      
    indices:
      - "^GSPC"  # S&P 500
      - "^IXIC"  # NASDAQ Composite
      - "^DJI"   # Dow Jones Industrial Average
      - "^VIX"   # CBOE Volatility Index
      - "^NSEI"  # NIFTY 50
      
    etfs:
      - "SPY"    # SPDR S&P 500 ETF
      - "QQQ"    # Invesco QQQ Trust
      - "IWM"    # iShares Russell 2000 ETF
      - "EEM"    # iShares MSCI Emerging Markets ETF
      
  # Default selections for UI
  default_symbols: "${DEFAULT_TICKERS:AAPL,MSFT,INFY.NS,TCS.NS}"
  default_period: "1y"  # 1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, max
  default_interval: "1d"  # 1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo

# -------------------------------
# User Interface Configuration
# -------------------------------
ui:
  # Streamlit configuration
  streamlit:
    theme: "${STREAMLIT_THEME:dark}"  # light, dark
    layout: "wide"  # centered, wide
    sidebar_state: "expanded"  # auto, expanded, collapsed
    
    # Page configuration
    page_title: "StockPredictionPro"
    page_icon: "📈"
    menu_items:
      'Get Help': 'https://github.com/Faraazz05/StockPredictionPro/wiki'
      'Report a bug': 'https://github.com/Faraazz05/StockPredictionPro/issues'
      'About': """
        # StockPredictionPro v1.0.0
        Advanced Stock Market Prediction with Machine Learning
        
        Built with ❤️ using Streamlit, scikit-learn, and Plotly
        
        **Disclaimer**: This application is for educational purposes only.
        Not financial advice. Trade at your own risk.
      """
  
  # Display preferences
  display:
    max_symbols_per_request: 10
    max_data_points_chart: 2000
    default_chart_height: 400
    show_advanced_options: false
    enable_animations: true
    
  # Navigation and pages
  navigation:
    show_page_numbers: true
    enable_sidebar_navigation: true
    
    # Page visibility (can disable pages if needed)
    pages:
      overview: true
      data_indicators: true
      chart_analysis: true
      regression_models: true
      classification_models: true
      model_comparison: true
      trading_signals: true
      portfolio_management: true
      backtest_performance: true
      exports_reports: true
      admin_logs: true

# -------------------------------
# Data Processing Configuration
# -------------------------------
data_processing:
  # Data validation
  validation:
    min_data_points: 50
    max_missing_ratio: 0.1  # 10% missing data allowed
    outlier_threshold: 5.0  # standard deviations
    
  # Data cleaning
  cleaning:
    fill_method: "forward"  # forward, backward, interpolate, drop
    max_fill_days: 5
    remove_weekends: false
    adjust_for_splits: true
    adjust_for_dividends: true
    
  # Feature engineering
  features:
    max_lag_periods: 10
    polynomial_degree_limit: 3
    interaction_features: false
    
  # Memory management
  memory:
    max_cache_size_mb: 500
    auto_cleanup_threshold: 0.8
    cache_compression: true

# -------------------------------
# Caching Configuration
# -------------------------------
caching:
  enabled: true
  
  # Cache backends
  backend:
    type: "memory"  # memory, redis, file
    redis_url: "${REDIS_URL:}"
    file_cache_dir: "data/cache"
    
  # Cache TTL settings (seconds)
  ttl:
    stock_data: 3600      # 1 hour
    indicators: 1800      # 30 minutes
    models: 86400         # 24 hours
    predictions: 300      # 5 minutes
    backtests: 7200       # 2 hours
    charts: 600           # 10 minutes
    
  # Cache size limits
  size_limits:
    max_entries: 1000
    max_size_mb: 256
    
  # Cache keys configuration
  keys:
    prefix: "stockpred"
    include_version: true
    include_user_context: false

# -------------------------------
# Performance Configuration
# -------------------------------
performance:
  # Concurrency settings
  concurrency:
    max_workers: 4
    enable_multiprocessing: false  # Set true for CPU-intensive tasks
    
  # Timeouts
  timeouts:
    data_fetch: 30
    model_training: 300   # 5 minutes
    prediction: 10
    chart_generation: 15
    
  # Memory limits
  memory:
    max_dataframe_size_mb: 100
    enable_memory_monitoring: true
    gc_threshold: 0.8
    
  # Optimization flags
  optimization:
    use_numba: false      # JIT compilation (install numba if enabled)
    vectorized_operations: true
    lazy_loading: true
    precompute_indicators: false

# -------------------------------
# Logging Configuration
# -------------------------------
logging:
  # Log levels by component
  levels:
    root: "INFO"
    data: "INFO"
    models: "INFO"
    ui: "WARNING"
    trading: "INFO"
    api: "INFO"
    
  # Log destinations
  handlers:
    console:
      enabled: true
      level: "INFO"
      format: "simple"
      
    file:
      enabled: true
      level: "DEBUG"
      rotation: "daily"
      retention: 7  # days
      max_size: "10MB"
      
    error_file:
      enabled: true
      level: "ERROR"
      
  # Structured logging
  structured:
    enabled: false
    format: "json"
    
  # Log filtering
  filters:
    exclude_patterns:
      - "healthcheck"
      - "favicon.ico"
    
  # Performance logging
  performance:
    log_slow_operations: true
    slow_threshold_seconds: 1.0

# -------------------------------
# Security Configuration
# -------------------------------
security:
  # Data protection
  data_protection:
    encrypt_sensitive_data: false
    hash_user_inputs: false
    sanitize_inputs: true
    
  # Rate limiting (application level)
  rate_limiting:
    enabled: false
    requests_per_minute: 60
    
  # CORS (for API integration)
  cors:
    enabled: true
    allowed_origins: ["*"]
    
  # Content Security Policy
  csp:
    enabled: false
    policy: "default-src 'self'"

# -------------------------------
# Feature Flags
# -------------------------------
features:
  # Core features
  data_fetching: true
  model_training: true
  predictions: true
  backtesting: true
  
  # Advanced features
  real_time_data: false
  portfolio_optimization: false
  options_analysis: false
  fundamental_analysis: false
  
  # Experimental features
  experimental:
    auto_trading: false
    sentiment_analysis: false
    news_integration: false
    social_media_data: false
    
  # UI features
  ui_features:
    dark_theme: true
    export_functionality: true
    advanced_charts: true
    custom_indicators: false
    
  # API features (if API is enabled)
  api_features:
    webhook_notifications: false
    batch_processing: false
    scheduled_jobs: false

# -------------------------------
# Internationalization
# -------------------------------
i18n:
  enabled: false
  default_language: "en"
  supported_languages:
    - "en"  # English
    - "hi"  # Hindi (future)
    - "es"  # Spanish (future)
    
  # Currency and number formatting
  formatting:
    currency_symbol: "₹"  # ₹ for INR, $ for USD
    number_format: "en_IN"
    date_format: "DD/MM/YYYY"
    time_format: "24h"

# -------------------------------
# Integrations
# -------------------------------
integrations:
  # External services
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    
  notifications:
    enabled: false
    services: []  # slack, discord, telegram
    
  cloud_storage:
    enabled: false
    provider: "aws"  # aws, gcp, azure
    
  analytics:
    enabled: false
    google_analytics: ""
    
# -------------------------------
# Development Settings
# -------------------------------
development:
  # Development modes
  debug_mode: true
  hot_reload: true
  profiling: false
  
  # Mock data
  use_mock_data: false
  mock_data_path: "tests/fixtures/mock_data"
  
  # Testing
  testing:
    run_quick_tests: false
    skip_slow_operations: false
    
# -------------------------------
# Backup and Recovery
# -------------------------------
backup:
  enabled: false
  
  # Automated backups
  schedule:
    data_backup: "0 2 * * *"    # Daily at 2 AM
    model_backup: "0 3 * * 0"   # Weekly on Sunday at 3 AM
    
  # Backup storage
  storage:
    local_path: "backups/"
    retention_days: 30
    compression: true
    
# -------------------------------
# Governance and Audit
# -------------------------------
governance:
  # Audit trails
  audit:
    enabled: "${ENABLE_AUDIT_TRAILS:true}"
    log_user_actions: true
    log_model_training: true
    log_predictions: true
    
  # Compliance
  compliance:
    data_retention_days: 365
    log_retention_days: 90
    
  # Metadata
  metadata:
    include_git_info: true
    include_environment_info: true
    include_performance_metrics: true
    author: "${RUN_METADATA_AUTHOR:Anonymous}"

# -------------------------------
# Alerts and Notifications
# -------------------------------
alerts:
  enabled: false
  
  # Alert conditions
  conditions:
    system_errors: true
    performance_degradation: true
    data_quality_issues: true
    
  # Alert channels
  channels:
    console: true
    file: true
    email: false
    slack: false
    
# -------------------------------
# Customization
# -------------------------------
customization:
  # Branding
  branding:
    logo_url: ""
    company_name: ""
    support_email: "sp_mohdfaraz@outlook.com"
    
  # Custom CSS
  styling:
    custom_css_file: "app/styles/custom.css"
    color_scheme: "default"  # default, custom
    
  # Custom components
  components:
    enable_custom_indicators: false
    enable_custom_models: false
